### ISSUE TITLE
@fluentui/react now fails

### ISSUE THREAD

**Issue by FallingSnow** [postui/esm.sh#48]
https://esm.sh/@fluentui/react@8.9.0
```js
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: Ambiguous import \"DateRangeType\" has multiple matching exports");
export default null;
```

Used to work but now displays this error.

**Comment by ije** [comment]
i will fix it ASAP, thanks @FallingSnow

**Comment by ije** [comment]
fixed, please try again, thanks

**Comment by FallingSnow** [comment]
Great, thank you! @fluentui/react now loads.

It seems `https://cdn.esm.sh/v38/@fluentui/utilities@8.0.3` is not produced correctly though.
```js
style-utilities.development.js:709 Uncaught (in promise) SyntaxError: The requested module '../../utilities@8.0.3/deno/utilities.development.js' does not provide an export named 'IsFocusVisibleClassName'
async function (async)
bootstrap @ bootstrap.ts:18
(anonymous) @ main.js:3
```

It is exported:
https://github.com/microsoft/fluentui/blob/dab45a2afe609709735b9b6e604a1af40d50e809/packages/utilities/src/index.ts#L74

**Comment by FallingSnow** [comment]
The following does work.
```js
$ npm install @fluentui/utilities
$ node
Welcome to Node.js v15.5.0.
Type ".help" for more information.
> require('@fluentui/utilities').IsFocusVisibleClassName
'ms-Fabric--isFocusVisible'
```

**Comment by FallingSnow** [comment]
Hmmm, seems to be a new error today:
https://cdn.esm.sh/@fluentui/utilities@8.0.3
```js
/* esm.sh - error */
throw new Error("[esm.sh] " + "bucket not found");
export default null;
```

**Comment by ije** [comment]
fixed, it is a bug by upgrading the postdb mod, sorry for that!

**Comment by FallingSnow** [comment]
No worries. The `IsFocusVisibleClassName` error still persists though.

**Comment by FallingSnow** [comment]
Ok so if we look at `.aleph/development/-/cdn.esm.sh/v40/@fluentui/utilities@8.0.4/deno/utilities.development.js` we see
```js
__export(lib_exports, {
...
   IsFocusVisibleClassName: ()=>IsFocusVisibleClassName
...
}
```

However if we look at the `var { ... } = lib_exports;` line at the end of the file, `IsFocusVisibleClassName` is no where to be found.

**Comment by FallingSnow** [comment]
Also it does seem that esbuild does export this correctly.

Install dependencies:
```js
$ yarn add esbuild react react-dom @fluentui/react
```


Create app.ts:
```js
import * as out from "@fluentui/react";
console.log(out);
```

Compile and run (node/browser preset):
```js
$ ./node_modules/.bin/esbuild app.ts --bundle --platform=node --outfile=out.js
$  node out.js
ms-Fabric--isFocusVisible

$ ./node_modules/.bin/esbuild app.ts --bundle --platform=browser --outfile=out.js
$  node out.js
ms-Fabric--isFocusVisible
```

**Comment by ije** [comment]
@FallingSnow thanks for the details, i will look into it!

**Comment by ije** [comment]
fixed in `v44` branch
